dist: bionic
sudo: required
language: cpp

git:
  strategy: clone
  depth: 1
  quiet: false

addons:
  apt:
    packages:
    - libsdl2-2.0-0

install:
  - ./scripts/build_dependencies
  - ./scripts/build

script: echo "Success!"
