dist: focal
sudo: required
language: cpp

git:
  strategy: clone
  depth: 1
  quiet: false

addons:
  apt:
    packages:
    - libsdl2-2.0-0
    - libsdl2-dev
    - libsdl2-gfx-dev
    - libsdl2-image-2.0-0
    - libsdl2-image-dev
    - libsdl2-mixer-2.0-0
    - libsdl2-net-2.0-0
    - libsdl2-net-dev
    - libsdl2-ttf-2.0-0
    - libsdl2-ttf-dev
    - liblua5.3-dev

install:
  - ./scripts/build_dependencies
  - ./scripts/build

script: echo "Success!"
