#ifndef DEBUG_RENDER_VELOCITY_PROBES_COMPONENT_HPP
#define DEBUG_RENDER_VELOCITY_PROBES_COMPONENT_HPP

struct DebugRenderVelocityProbesComponent
{

};

#endif // DEBUG_RENDER_VELOCITY_PROBES_COMPONENT_HPP
